@extends('layouts.main')
@section('title', 'Gym training')
@section('assets')
    <link rel="stylesheet" href="{{ asset('css/classes.css') }}">
@endsection
@section('body')
    @include('layouts.nav')
    <div class="container">
        <div class="container-fluid">
            <div class="row">
                <h1 class="col-6">Gym Training</h1>
                <div class="col-6 end-alignment">
                    <a href="{{ route('landing-page') }}" class="btn btn-danger">Back</a>
                </div>
            </div>
            <div class="line"></div>
            <div class="row">
                <p class="col-12">
                    Gym Training or <i>Weight training</i> is a common type of strength training for developing the strength
                    and size of skeletal
                    muscles.[2] It
                    uses the force of gravity in the form of weighted bars, dumbbells or weight stacks in order to oppose
                    the force generated by muscle through concentric or eccentric contraction. Weight training uses a
                    variety of specialized equipment to target specific muscle groups and types of movement.

                    Sports in which weight training is used include bodybuilding, weightlifting, powerlifting, strongman,
                    highland games, hammer throw, shot put, discus throw, and javelin throw. Many other sports use strength
                    training as part of their training regimen, notably: American football, baseball, basketball, canoeing,
                    cricket, football, hockey, lacrosse, mixed martial arts, rowing, rugby league, rugby union, track and
                    field, boxing, wrestling and judo.
                </p>

                <p class="col-md-12">
                    You may feel increased mental and physical energy, a boost in alertness and enthusiasm, and fewer
                    negative feelings after getting into a routine of practicing yoga.
                </p>
            </div>

            <h4>Short History</h4>
            <div class="line"></div>
            <div class="row">
                <p class="col-md-12">
                    The genealogy of lifting can be traced back to the beginning of recorded history[3] where humanity's
                    fascination with physical abilities can be found among numerous ancient writings. In many prehistoric
                    tribes, they would have a big rock they would try to lift, and the first one to lift it would inscribe
                    their name into the stone. Such rocks have been found in Greek and Scottish castles.[4] Progressive
                    resistance training dates back at least to Ancient Greece, when legend has it that wrestler Milo of
                    Croton trained by carrying a newborn calf on his back every day until it was fully grown. Another Greek,
                    the physician Galen, described strength training exercises using the halteres (an early form of
                    dumbbell) in the 2nd century.

                    Ancient Greek sculptures also depict lifting feats. The weights were generally stones, but later gave
                    way to dumbbells. The dumbbell was joined by the barbell in the later half of the 19th century. Early
                    barbells had hollow globes that could be filled with sand or lead shot, but by the end of the century
                    these were replaced by the plate-loading barbell commonly used today.[5]

                    Another early device was the Indian club, which came from ancient India, where it was called the
                    "mugdar" or ''gada''. It subsequently became popular during the 19th century, and has recently made a
                    comeback in the form of the clubbell.

                    Weightlifting was first introduced in the Olympics in the 1896 Athens Olympic Games as a part of track
                    and field, and was officially recognized as its own event in 1914.[6]

                    The 1960s saw the gradual introduction of exercise machines into the still-rare strength training gyms
                    of the time. Weight training became increasingly popular in the 1970s, following the release of the
                    bodybuilding movie Pumping Iron, and the subsequent popularity of Arnold Schwarzenegger. Since the late
                    1990s, increasing numbers of women have taken up weight training; currently, nearly one in five U.S.
                    women engage in weight training on a regular basis.[7]
                </p>

                <strong class="col-md-12">Basic principles</strong>
                <p class="col-md-12">The basic principles of weight training are essentially identical to those of
                    strength training, and involve a manipulation of the number of repetitions (reps), sets, tempo, exercise
                    types, and weight moved to cause desired increases in strength, endurance, and size. The specific
                    combinations of reps, sets, exercises, and weights depends on the aims of the individual performing the
                    exercise.[8]

                    In addition to the basic principles of strength training, a further consideration added by weight
                    training is the equipment used.[2] Types of equipment include barbells, dumbbells, kettlebells, pulleys
                    and stacks in the form of weight machines, and the body's own weight in the case of chin-ups and
                    push-ups. Different types of weights will give different types of resistance, and often the same
                    absolute weight can have different relative weights depending on the type of equipment used. For
                    example, lifting 10 kilograms using a dumbbell sometimes requires more force than moving 10 kilograms on
                    a weight stack if certain pulley arrangements are used. In other cases, the weight stack may require
                    more force than the equivalent dumbbell weight due to additional torque or resistance in the machine.
                    Additionally, although they may display the same weight stack, different machines may be heavier or
                    lighter depending on the number of pulleys and their arrangements.

                    Weight training also requires the use of proper or 'good form', performing the movements with the
                    appropriate muscle group, and not transferring the weight to different body parts in order to move
                    greater weight (called 'cheating'). Failure to use good form during a training set can result in injury
                    or a failure to meet training goals. If the desired muscle group is not challenged sufficiently, the
                    threshold of overload is never reached and the muscle does not gain in strength. At a particularly
                    advanced level; however, "cheating" can be used to break through strength plateaus and encourage
                    neurological and muscular adaptation.</p>

                <p class="col-md-12">Physical fitness and mental stability go hand in hand, as research suggests that
                    although physical and aerobic activity betters ones physical capabilities, it also helps with ones
                    positive body image and self esteem. Studies show that physical fitness helps improve positive body
                    image and self esteem, perceivable increased stress management, reduction of depression and anxiety,[3]
                    as well as enhance mood states and improve overall cognitive function.[1] This all further shows the
                    importance behind the usage of physical fitness for mental stability and why it is so important to
                    engage in the practice of it.</p>
            </div>


            <div class="link-info bottom end-alignment mt-4"><a class="btn btn-info"
                    href="https://en.wikipedia.org/wiki/Weight_training" target="_blank">More Info about
                    Gym Training
                    (Wikipedia)</a>
            </div>
        </div>
    </div>
    @include('layouts.footer')
@endsection
